package entity;
// Generated Apr 1, 2019 6:40:54 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer id;
     private int rollno;
     private String name;
     private String email;
     private String password;
     private String sex;
     private String course;
     private double fee;
     private double paid;
     private double due;
     private String address;
     private String contact;

    public Student() {
    }

    public Student(int rollno, String name, String email, String password, String sex, String course, double fee, double paid, double due, String address, String contact) {
       this.rollno = rollno;
       this.name = name;
       this.email = email;
       this.password = password;
       this.sex = sex;
       this.course = course;
       this.fee = fee;
       this.paid = paid;
       this.due = due;
       this.address = address;
       this.contact = contact;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getRollno() {
        return this.rollno;
    }
    
    public void setRollno(int rollno) {
        this.rollno = rollno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public double getFee() {
        return this.fee;
    }
    
    public void setFee(double fee) {
        this.fee = fee;
    }
    public double getPaid() {
        return this.paid;
    }
    
    public void setPaid(double paid) {
        this.paid = paid;
    }
    public double getDue() {
        return this.due;
    }
    
    public void setDue(double due) {
        this.due = due;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }




}


